### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by marquez138** [hxu-stripe/terminal-example#1]
First of all thank you for posting this sample code. Can I ask what you would recommend to make this production ready?

**Comment by hxu-stripe** [comment]
I would actually recommend not trying to adapt this to production at all, as there's quite a lot that is not implemented (error handling, authentication, all your other business logic, etc).  Instead, you should use this as a reference for the specific API calls necessary for the Terminal bits, then just move those over into whichever production ready app you have.

Also, you have probably already seen these, but we have other samples that are also visible here (but again, also don't use these in production):
https://github.com/stripe/example-terminal-backend
https://github.com/stripe-samples/sample-terminal-ios-app

**Comment by marquez138** [comment]
Thanks again for the quick response. Do you have any plans to show a react js frontend sample? Im stuck on how to implement these functional components into a class component.

**Comment by hxu-stripe** [comment]
We already have one!  Take a look at this example app implemented in React JS.  It goes further and also implements things like reader registrations as well: https://github.com/stripe/stripe-terminal-js-demo

**Comment by marquez138** [comment]
Can i use a node js server backend with this example? current one is written in ruby

**Comment by hxu-stripe** [comment]
You can use whichever backend language of choice.  For Terminal, we only provide a Ruby sample.  For other sample backend implementations (but which are not Terminal specific), please take a look at this repo: https://github.com/stripe-samples/placing-a-hold

**Comment by marquez138** [comment]
Very helpful..can I ask once i implement the backend in node do i push it to heroku or can i test it locally? For example in the Connect to backend server input, can i put "https://localhost:5000" or do I have to use a heroku address? Sorry does that make sense?

**Comment by hxu-stripe** [comment]
You should be able to test locally.

If you have more questions, you can get in touch with us on IRC in #stripe on freenode.  Also, feel free to write in to support@stripe.com.

Good luck!
